const quotes = [
  { quote: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { quote: "Hard work is worthless for those who don't believe in themselves.", author: "Naruto Uzumaki" },
  { quote: "Power comes in response to a need, not a desire.", author: "Goku" },
  { quote: "It is our choices that show what we truly are, far more than our abilities.", author: "Albus Dumbledore" },
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { quote: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { quote: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { quote: "Success is not final, failure is not fatal.", author: "Winston Churchill" },
  { quote: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { quote: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
  { quote: "Do not go where the path may lead, go instead where there is no path.", author: "Ralph Waldo Emerson" },
  { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { quote: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { quote: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { quote: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { quote: "The mind is everything. What you think you become.", author: "Buddha" },
  { quote: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { quote: "What we think, we become.", author: "Buddha" },
  { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { quote: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { quote: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { quote: "You have power over your mind, not outside events.", author: "Marcus Aurelius" },
  { quote: "The unexamined life is not worth living.", author: "Socrates" },
  { quote: "I think, therefore I am.", author: "Rene Descartes" },
  { quote: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { quote: "Man is condemned to be free.", author: "Jean-Paul Sartre" },
  { quote: "Give me liberty, or give me death!", author: "Patrick Henry" },
  { quote: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali" },
  { quote: "I have a dream that one day this nation will rise up.", author: "Martin Luther King Jr." },
  { quote: "Ask not what your country can do for you.", author: "John F. Kennedy" },
  { quote: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { quote: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { quote: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { quote: "Two roads diverged in a wood, and I took the one less traveled by.", author: "Robert Frost" },
  { quote: "To be or not to be, that is the question.", author: "William Shakespeare" },
  { quote: "All that glitters is not gold.", author: "William Shakespeare" },
  { quote: "The pen is mightier than the sword.", author: "Edward Bulwer-Lytton" },
  { quote: "Knowledge is power.", author: "Francis Bacon" },
  { quote: "Fortune favors the bold.", author: "Virgil" },
  { quote: "Carpe diem. Seize the day.", author: "Horace" },
  { quote: "An eye for an eye will only make the whole world blind.", author: "Mahatma Gandhi" },
  { quote: "Spread love everywhere you go.", author: "Mother Teresa" },
  { quote: "Peace begins with a smile.", author: "Mother Teresa" },
  { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { quote: "Yesterday is history, tomorrow is a mystery, today is a gift.", author: "Eleanor Roosevelt" },
  { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
  { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { quote: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
  { quote: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
  { quote: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
  { quote: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { quote: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { quote: "Nearly all men can stand adversity, but if you want to test a man's character, give him power.", author: "Abraham Lincoln" },
  { quote: "Try not to become a person of success, but rather try to become a person of value.", author: "Albert Einstein" },
  { quote: "The only source of knowledge is experience.", author: "Albert Einstein" },
  { quote: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
  { quote: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { quote: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott" },
  { quote: "It is never too late to be what you might have been.", author: "George Eliot" },
  { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { quote: "Comparison is the thief of joy.", author: "Theodore Roosevelt" },
  { quote: "Courage is not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
  { quote: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { quote: "A winner is a dreamer who never gives up.", author: "Nelson Mandela" },
  { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { quote: "Real generosity toward the future lies in giving all to the present.", author: "Albert Camus" },
  { quote: "In the depth of winter, I finally learned that within me there lay an invincible summer.", author: "Albert Camus" },
  { quote: "Freedom is what you do with what's been done to you.", author: "Jean-Paul Sartre" },
  { quote: "Life has no meaning a priori. It is up to you to give it a meaning.", author: "Jean-Paul Sartre" },
  { quote: "One cannot think well, love well, sleep well, if one has not dined well.", author: "Virginia Woolf" },
  { quote: "You cannot swim for new horizons until you have courage to lose sight of the shore.", author: "William Faulkner" },
  { quote: "The world breaks everyone, and afterward, many are strong at the broken places.", author: "Ernest Hemingway" },
  { quote: "Courage is grace under pressure.", author: "Ernest Hemingway" },
  { quote: "There is nothing to writing. All you do is sit down at a typewriter and bleed.", author: "Ernest Hemingway" },
  { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { quote: "Compassion and tolerance are not a sign of weakness, but a sign of strength.", author: "Dalai Lama" },
  { quote: "Be kind whenever possible. It is always possible.", author: "Dalai Lama" },
  { quote: "Once you replace negative thoughts with positive ones, you'll start having positive results.", author: "Willie Nelson" },
  { quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { quote: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { quote: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
  { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { quote: "Wherever you go, go with all your heart.", author: "Confucius" },
  { quote: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
  { quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
  { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
  { quote: "Believe in yourself and all that you are.", author: "Christian D. Larson" },
  { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { quote: "Some of us think holding on makes us strong, but sometimes it is letting go.", author: "Hermann Hesse" },
  { quote: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
  { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { quote: "When the student is ready, the teacher will appear.", author: "Buddhist Proverb" },
  { quote: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { quote: "The bamboo that bends is stronger than the oak that resists.", author: "Japanese Proverb" },
  { quote: "Vision without action is merely a dream.", author: "Joel Barker" },
  { quote: "Great things are done by a series of small things brought together.", author: "Vincent Van Gogh" },
  { quote: "I would rather die of passion than of boredom.", author: "Vincent Van Gogh" },
  { quote: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { quote: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
  { quote: "Art washes away from the soul the dust of everyday life.", author: "Pablo Picasso" },
  { quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { quote: "Every artist was first an amateur.", author: "Ralph Waldo Emerson" },
  { quote: "For every minute you are angry you lose sixty seconds of happiness.", author: "Ralph Waldo Emerson" },
  { quote: "Our greatest fear should not be of failure but of succeeding at things that don't matter.", author: "Francis Chan" },
  { quote: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { quote: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { quote: "Well done is better than well said.", author: "Benjamin Franklin" },
  { quote: "Either write something worth reading or do something worth writing.", author: "Benjamin Franklin" },
  { quote: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin" },
  { quote: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
  { quote: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus" },
  { quote: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus" },
  { quote: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali" },
  { quote: "Service to others is the rent you pay for your room here on earth.", author: "Muhammad Ali" },
  { quote: "Difficulties in life are intended to make us better, not bitter.", author: "Dan Reeves" },
  { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
  { quote: "Things do not change; we change.", author: "Henry David Thoreau" },
  { quote: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { quote: "It's hard to beat a person who never gives up.", author: "Babe Ruth" },
  { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { quote: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney" },
  { quote: "If you can dream it, you can do it.", author: "Walt Disney" },
  { quote: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Walt Whitman" },
  { quote: "Do I contradict myself? Very well, then I contradict myself.", author: "Walt Whitman" },
  { quote: "Twenty years from now you will be more disappointed by the things you didn't do.", author: "Mark Twain" },
  { quote: "Get busy living or get busy dying.", author: "Stephen King" },
  { quote: "Fear is the mind-killer.", author: "Frank Herbert" },
  { quote: "The truth may be puzzling. It may take some work to grapple with.", author: "Carl Sagan" },
  { quote: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
  { quote: "We are all connected; to each other, biologically, to the earth, chemically.", author: "Neil deGrasse Tyson" },
  { quote: "The universe is under no obligation to make sense to you.", author: "Neil deGrasse Tyson" },
  { quote: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
  { quote: "That's one small step for man, one giant leap for mankind.", author: "Neil Armstrong" },
  { quote: "Failure is simply the opportunity to begin again, this time more wisely.", author: "Henry Ford" },
  { quote: "Quality means doing it right when no one is looking.", author: "Henry Ford" },
  { quote: "Coming together is a beginning, staying together is progress.", author: "Henry Ford" },
  { quote: "The world is a book, and those who do not travel read only one page.", author: "Saint Augustine" },
  { quote: "A ship in harbor is safe, but that is not what ships are built for.", author: "John A. Shedd" },
  { quote: "The cave you fear to enter holds the treasure you seek.", author: "Joseph Campbell" },
  { quote: "Follow your bliss and the universe will open doors for you.", author: "Joseph Campbell" },
  { quote: "We must be willing to let go of the life we planned so as to have the life that is waiting for us.", author: "Joseph Campbell" },
  { quote: "There is no coming to consciousness without pain.", author: "Carl Jung" },
  { quote: "Who looks outside, dreams; who looks inside, awakes.", author: "Carl Jung" },
  { quote: "The privilege of a lifetime is to become who you truly are.", author: "Carl Jung" },
  { quote: "Everything that irritates us about others can lead us to an understanding of ourselves.", author: "Carl Jung" },
  { quote: "Man's mind, once stretched by a new idea, never regains its original dimensions.", author: "Oliver Wendell Holmes" },
  { quote: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
  { quote: "Excellence is not an act, but a habit.", author: "Aristotle" },
  { quote: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { quote: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { quote: "Patience is bitter, but its fruit is sweet.", author: "Aristotle" },
  { quote: "The whole is greater than the sum of its parts.", author: "Aristotle" },
  { quote: "One who fears death cannot enjoy life.", author: "Chanakya" },
  { quote: "A person should not be too honest. Straight trees are cut first.", author: "Chanakya" },
  { quote: "Before you start some work, always ask yourself three questions.", author: "Chanakya" },
  { quote: "There is some good in the worst of us and some evil in the best of us.", author: "Chanakya" },
  { quote: "Test a servant while in the discharge of his duty.", author: "Chanakya" },
  { quote: "Even if snake is not poisonous, it should pretend to be venomous.", author: "Chanakya" },
  { quote: "As soon as fear approaches near, attack and destroy it.", author: "Chanakya" },
  { quote: "The biggest guru mantra is: never share your secrets with anybody.", author: "Chanakya" },
  { quote: "God is not present in idol nor in your heart. He is present in your good deed.", author: "Chanakya" },
  { quote: "Do not reveal what you have thought upon doing, but be advised only after having done it.", author: "Chanakya" },
  { quote: "It's not the strongest of the species that survives, but the most adaptable.", author: "Charles Darwin" },
  { quote: "A man who dares to waste one hour of time has not discovered the value of life.", author: "Charles Darwin" },
  { quote: "Ignorance more frequently begets confidence than does knowledge.", author: "Charles Darwin" },
  { quote: "I love fools' experiments. I am always making them.", author: "Charles Darwin" },
  { quote: "Time you enjoy wasting is not wasted time.", author: "Marthe Troly-Curtin" },
  { quote: "The greatest wealth is to live content with little.", author: "Plato" },
  { quote: "Wise men speak because they have something to say; fools because they have to say something.", author: "Plato" },
  { quote: "At the touch of love everyone becomes a poet.", author: "Plato" },
  { quote: "Necessity is the mother of invention.", author: "Plato" },
  { quote: "The measure of a man is what he does with power.", author: "Plato" },
  { quote: "He was a wise man who invented beer.", author: "Plato" },
  { quote: "Music gives a soul to the universe, wings to the mind, flight to the imagination.", author: "Plato" },
  { quote: "The beginning is the most important part of the work.", author: "Plato" },
  { quote: "We can easily forgive a child who is afraid of the dark.", author: "Plato" },
  { quote: "Ideas are the source of everything.", author: "Ernest Dimnet" },
  { quote: "You can discover more about a person in an hour of play than in a year of conversation.", author: "Plato" },
  { quote: "Everything that has a beginning has an end.", author: "The Matrix" },
  { quote: "There is no spoon.", author: "The Matrix" },
  { quote: "Fate, it seems, is not without a sense of irony.", author: "The Matrix" },
  { quote: "May the Force be with you.", author: "Star Wars" },
  { quote: "Do or do not, there is no try.", author: "Yoda" },
  { quote: "Fear is the path to the dark side.", author: "Yoda" },
  { quote: "The greatest teacher, failure is.", author: "Yoda" },
  { quote: "Named must your fear be before banish it you can.", author: "Yoda" },
  { quote: "In a dark place we find ourselves, and a little more knowledge lights our way.", author: "Yoda" },
  { quote: "Truly wonderful the mind of a child is.", author: "Yoda" },
  { quote: "Wars not make one great.", author: "Yoda" },
  { quote: "Your focus determines your reality.", author: "Qui-Gon Jinn" },
  { quote: "Difficult to see. Always in motion is the future.", author: "Yoda" },
  { quote: "Life finds a way.", author: "Ian Malcolm, Jurassic Park" },
  { quote: "With great power comes great responsibility.", author: "Uncle Ben, Spider-Man" },
  { quote: "Why do we fall? So we can learn to pick ourselves up.", author: "Alfred, Batman Begins" },
  { quote: "It's not who I am underneath, but what I do that defines me.", author: "Batman" },
  { quote: "The night is darkest just before the dawn.", author: "Harvey Dent, The Dark Knight" },
  { quote: "You either die a hero, or you live long enough to see yourself become the villain.", author: "Harvey Dent" },
  { quote: "Some men just want to watch the world burn.", author: "Alfred, The Dark Knight" },
  { quote: "I'm gonna make him an offer he can't refuse.", author: "Vito Corleone, The Godfather" },
  { quote: "Keep your friends close, but your enemies closer.", author: "Michael Corleone, The Godfather" },
  { quote: "Life is like a box of chocolates, you never know what you're gonna get.", author: "Forrest Gump" },
  { quote: "Stupid is as stupid does.", author: "Forrest Gump" },
  { quote: "After all this time? Always.", author: "Severus Snape" },
  { quote: "Happiness can be found even in the darkest of times.", author: "Albus Dumbledore" },
  { quote: "It is our choices that show what we truly are.", author: "Albus Dumbledore" },
  { quote: "Fear of a name only increases fear of the thing itself.", author: "Albus Dumbledore" },
  { quote: "It does not do to dwell on dreams and forget to live.", author: "Albus Dumbledore" },
  { quote: "Words are, in my not-so-humble opinion, our most inexhaustible source of magic.", author: "Albus Dumbledore" },
  { quote: "One day, Harry, the world may be in need of a savior.", author: "Albus Dumbledore" },
  { quote: "The truth. It is a beautiful and terrible thing.", author: "Albus Dumbledore" },
  { quote: "Winter is coming.", author: "Ned Stark, Game of Thrones" },
  { quote: "When you play the game of thrones, you win or you die.", author: "Cersei Lannister" },
  { quote: "A Lannister always pays his debts.", author: "Tyrion Lannister" },
  { quote: "I drink and I know things.", author: "Tyrion Lannister" },
  { quote: "Chaos is a ladder.", author: "Petyr Baelish" },
  { quote: "The night is dark and full of terrors.", author: "Melisandre" },
  { quote: "Valar Morghulis.", author: "Game of Thrones" },
  { quote: "Hodor.", author: "Hodor, Game of Thrones" },
  { quote: "Live long and prosper.", author: "Spock, Star Trek" },
  { quote: "Logic is the beginning of wisdom, not the end.", author: "Spock" },
  { quote: "Change is the essential process of all existence.", author: "Spock" },
  { quote: "I have been, and always shall be, your friend.", author: "Spock" },
  { quote: "The needs of the many outweigh the needs of the few.", author: "Spock" },
  { quote: "There are things worse than death.", author: "James T. Kirk" },
  { quote: "Frankly, my dear, I don't give a damn.", author: "Rhett Butler, Gone with the Wind" },
  { quote: "Tomorrow is another day.", author: "Scarlett O'Hara" },
  { quote: "I'll be back.", author: "The Terminator" },
  { quote: "Hasta la vista, baby.", author: "The Terminator" },
  { quote: "Say hello to my little friend!", author: "Tony Montana, Scarface" },
  { quote: "The first rule of Fight Club is: you do not talk about Fight Club.", author: "Tyler Durden" },
  { quote: "It's only after we've lost everything that we're free to do anything.", author: "Tyler Durden" },
  { quote: "You are not your job. You're not how much money you have.", author: "Tyler Durden" },
  { quote: "This is your life, and it's ending one minute at a time.", author: "Tyler Durden" },
  { quote: "Sometimes you win, sometimes you lose.", author: "Rocky Balboa" },
  { quote: "It ain't about how hard you hit. It's about how hard you can get hit and keep moving forward.", author: "Rocky Balboa" },
  { quote: "Every champion was once a contender who refused to give up.", author: "Rocky Balboa" },
  { quote: "The world ain't all sunshine and rainbows.", author: "Rocky Balboa" },
  { quote: "I feel the need — the need for speed.", author: "Top Gun" },
  { quote: "Just keep swimming.", author: "Dory, Finding Nemo" },
  { quote: "To infinity and beyond!", author: "Buzz Lightyear" },
  { quote: "You've got a friend in me.", author: "Woody, Toy Story" },
  { quote: "Hakuna Matata. It means no worries.", author: "Timon, The Lion King" },
  { quote: "Remember who you are.", author: "Mufasa, The Lion King" },
  { quote: "It is time.", author: "Mufasa, The Lion King" },
  { quote: "The best in life are free.", author: "The Lion King" },
  { quote: "Let it go, let it go, can't hold it back anymore.", author: "Elsa, Frozen" },
  { quote: "Some people are worth melting for.", author: "Olaf, Frozen" },
  { quote: "I am Groot.", author: "Groot, Guardians of the Galaxy" },
  { quote: "I am Iron Man.", author: "Tony Stark" },
  { quote: "Whatever it takes.", author: "Iron Man, Avengers Endgame" },
  { quote: "I can do this all day.", author: "Captain America" },
  { quote: "Avengers, assemble.", author: "Captain America" },
  { quote: "Part of the journey is the end.", author: "Tony Stark" },
  { quote: "In time, you will know what it's like to lose.", author: "Thanos" },
  { quote: "Reality is often disappointing.", author: "Thanos" },
  { quote: "I am inevitable.", author: "Thanos" },
  { quote: "Perfectly balanced, as all things should be.", author: "Thanos" },
  { quote: "Sometimes the best way to solve your own problems is to help someone else.", author: "Uncle Iroh, Avatar: The Last Airbender" },
  { quote: "Pride is not the opposite of shame, but its source.", author: "Uncle Iroh" },
  { quote: "It is important to draw wisdom from many different places.", author: "Uncle Iroh" },
  { quote: "Destiny is a funny thing. You never know how things are going to work out.", author: "Uncle Iroh" },
  { quote: "Failure is only the opportunity to begin again more intelligently.", author: "Uncle Iroh" },
  { quote: "Sharing is caring.", author: "Barney the Dinosaur" },
  { quote: "Adventure is out there!", author: "Up" },
  { quote: "Adversity is like a strong wind. It tears away from us all but the things that cannot be torn.", author: "Arthur Golden" },
  { quote: "It matters not what someone is born, but what they grow to be.", author: "Albus Dumbledore" },
  { quote: "I solemnly swear that I am up to no good.", author: "Harry Potter" },
  { quote: "Never trust anything that can think for itself if you can't see where it keeps its brain.", author: "Arthur Weasley" },
  { quote: "You're a wizard, Harry.", author: "Rubeus Hagrid" },
  { quote: "It is the unknown we fear when we look upon death and darkness.", author: "Albus Dumbledore" },
  { quote: "The show must go on.", author: "Queen" },
  { quote: "We will, we will rock you.", author: "Queen" },
  { quote: "I want it that way.", author: "Backstreet Boys" },
  { quote: "Money can't buy happiness, but it can buy a boat big enough to sail right up to it.", author: "Unknown" },
  { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { quote: "Speak softly and carry a big stick.", author: "Theodore Roosevelt" },
  { quote: "The credit belongs to the man who is actually in the arena.", author: "Theodore Roosevelt" },
  { quote: "Do what you feel in your heart to be right, for you'll be criticized anyway.", author: "Eleanor Roosevelt" },
  { quote: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { quote: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { quote: "It is not the critic who counts.", author: "Theodore Roosevelt" },
  { quote: "The strongest of all warriors are these two — Time and Patience.", author: "Leo Tolstoy" },
  { quote: "Everyone thinks of changing the world, but no one thinks of changing himself.", author: "Leo Tolstoy" },
  { quote: "If you want to be happy, be.", author: "Leo Tolstoy" },
  { quote: "All happy families are alike; each unhappy family is unhappy in its own way.", author: "Leo Tolstoy" },
  { quote: "There is no greatness where there is not simplicity, goodness, and truth.", author: "Leo Tolstoy" },
  { quote: "One cannot be forced to love, but love can be a means of teaching.", author: "Leo Tolstoy" },
  { quote: "History is nothing but a collection of fables agreed upon.", author: "Napoleon Bonaparte" },
  { quote: "A leader is a dealer in hope.", author: "Napoleon Bonaparte" },
  { quote: "Never interrupt your enemy when he is making a mistake.", author: "Napoleon Bonaparte" },
  { quote: "Impossible is a word to be found only in the dictionary of fools.", author: "Napoleon Bonaparte" },
  { quote: "Glory is fleeting, but obscurity is forever.", author: "Napoleon Bonaparte" },
  { quote: "Circumstances? I make circumstances.", author: "Napoleon Bonaparte" },
  { quote: "The world suffers a lot. Not because of the violence of bad people.", author: "Napoleon Bonaparte" },
  { quote: "Four hostile newspapers are more to be feared than a thousand bayonets.", author: "Napoleon Bonaparte" },
  { quote: "In politics, absurdity is not a handicap.", author: "Napoleon Bonaparte" },
  { quote: "Genius is nothing but a great capacity for patience.", author: "Georges-Louis Leclerc de Buffon" },
  { quote: "Let food be thy medicine and medicine be thy food.", author: "Hippocrates" },
  { quote: "Wherever the art of medicine is loved, there is also a love of humanity.", author: "Hippocrates" },
  { quote: "Life is short, art long, opportunity fleeting.", author: "Hippocrates" },
  { quote: "Healing is a matter of time, but it is sometimes also a matter of opportunity.", author: "Hippocrates" },
  { quote: "Extreme remedies are most appropriate for extreme diseases.", author: "Hippocrates" },
  { quote: "Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.", author: "Archimedes" },
  { quote: "Eureka!", author: "Archimedes" },
  { quote: "Mathematics is the language in which God has written the universe.", author: "Galileo Galilei" },
  { quote: "And yet it moves.", author: "Galileo Galilei" },
  { quote: "All truths are easy to understand once they are discovered.", author: "Galileo Galilei" },
  { quote: "You cannot teach a man anything; you can only help him find it within himself.", author: "Galileo Galilei" },
  { quote: "If I have seen further, it is by standing on the shoulders of giants.", author: "Isaac Newton" },
  { quote: "To every action there is always opposed an equal reaction.", author: "Isaac Newton" },
  { quote: "I can calculate the motion of heavenly bodies, but not the madness of people.", author: "Isaac Newton" },
  { quote: "Tact is the art of making a point without making an enemy.", author: "Isaac Newton" },
  { quote: "No great discovery was ever made without a bold guess.", author: "Isaac Newton" },
  { quote: "Energy cannot be created or destroyed, it can only be changed from one form to another.", author: "Albert Einstein" },
  { quote: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
  { quote: "Anyone who has never made a mistake has never tried anything new.", author: "Albert Einstein" },
  { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { quote: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", author: "Albert Einstein" },
  { quote: "God does not play dice with the universe.", author: "Albert Einstein" },
  { quote: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein" },
  { quote: "The measure of intelligence is the ability to change.", author: "Albert Einstein" },
  { quote: "It is the supreme art of the teacher to awaken joy in creative expression.", author: "Albert Einstein" },
  { quote: "Weakness of attitude becomes weakness of character.", author: "Albert Einstein" },
  { quote: "The only real valuable thing is intuition.", author: "Albert Einstein" },
  { quote: "Look deep into nature, and then you will understand everything better.", author: "Albert Einstein" },
  { quote: "Great spirits have always encountered violent opposition from mediocre minds.", author: "Albert Einstein" },
  { quote: "The world is a dangerous place, not because of those who do evil, but those who look on and do nothing.", author: "Albert Einstein" },
  { quote: "You can't blame gravity for falling in love.", author: "Albert Einstein" },
  { quote: "A ship is always safe at the shore, but that is not what it is built for.", author: "Albert Einstein" },
  { quote: "Once we accept our limits, we go beyond them.", author: "Albert Einstein" },
  { quote: "I have no special talent. I am only passionately curious.", author: "Albert Einstein" },
  { quote: "Peace cannot be kept by force; it can only be achieved by understanding.", author: "Albert Einstein" },
  { quote: "Learn from yesterday, live for today, hope for tomorrow.", author: "Albert Einstein" },
  { quote: "Any fool can know. The point is to understand.", author: "Albert Einstein" },
  { quote: "Reality is merely an illusion, albeit a very persistent one.", author: "Albert Einstein" },
  { quote: "I never think of the future - it comes soon enough.", author: "Albert Einstein" },
  { quote: "The only thing that interferes with my learning is my education.", author: "Albert Einstein" },
  { quote: "If you can't explain it simply, you don't understand it well enough.", author: "Albert Einstein" },
  { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { quote: "It's not that I'm so smart, it's just that I stay with problems longer.", author: "Albert Einstein" },
  { quote: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
  { quote: "The gift of fantasy has meant more to me than my talent for absorbing knowledge.", author: "Albert Einstein" },
  { quote: "The environment is everything that isn't me.", author: "Albert Einstein" },
  { quote: "Small is the number of people who see with their eyes and think with their minds.", author: "Albert Einstein" },
  { quote: "If A is success in life, then A equals x plus y plus z.", author: "Albert Einstein" },
  { quote: "Only a life lived for others is a life worthwhile.", author: "Albert Einstein" },
  { quote: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein" },
  { quote: "Bow down to no man; keep your own dignity always in front of you.", author: "Emiya Kiritsugu" },
  { quote: "People die if they are killed.", author: "Emiya Shirou" },
  { quote: "I am the bone of my sword.", author: "Emiya Shirou" },
  { quote: "Unlimited Blade Works.", author: "Emiya Shirou" },
  { quote: "There is no beauty in perfection.", author: "Emiya Shirou" },
  { quote: "Sometimes losing your way is part of the journey.", author: "Uncle Iroh" },
  { quote: "Even in the deepest darkness, hope can be found if you look for it.", author: "Aang" },
  { quote: "Everyone deserves a fair trial.", author: "Aang" },
  { quote: "You can't just control the elements, you have to be one with them.", author: "Aang" },
  { quote: "It's time to look inward and start asking, what are you gonna do now?", author: "Toph Beifong" },
  { quote: "I'm not afraid of storms, for I am learning how to sail my ship.", author: "Katara" },
  { quote: "Never give up without a fight.", author: "Katara" },
  { quote: "It's not the size of the dog in the fight, it's the size of the fight in the dog.", author: "Mark Twain" },
  { quote: "I am the strongest, but that's not why I win. I win because I never give up.", author: "Monkey D. Luffy" },
  { quote: "If you don't take risks, you can't create a future!", author: "Monkey D. Luffy" },
  { quote: "Inherited will, the destiny of the age, and the dreams of the people.", author: "Gol D. Roger" },
  { quote: "When do you think people die? When they are shot through the heart by a bullet?", author: "Dr. Hiluluk, One Piece" },
  { quote: "A single Robin fought for the world's freedom of scholarship until the very end.", author: "One Piece" },
  { quote: "I don't want to conquer anything. I just think the guy with the most freedom in this whole ocean is the Pirate King!", author: "Monkey D. Luffy" },
  { quote: "Being a coward is not a bad thing at all. It's a gift.", author: "Usopp" },
  { quote: "Whatever you lose, you'll find it again. But what you throw away you'll never get back.", author: "Kuzan, One Piece" },
  { quote: "Fools who don't respect the past are likely to repeat it.", author: "Nico Robin" },
  { quote: "The world is not perfect, but it's there for us doing the best it can.", author: "Roy Mustang, Fullmetal Alchemist" },
  { quote: "A lesson without pain is meaningless.", author: "Edward Elric" },
  { quote: "In this world, there is a truth that is absolute: people cannot gain anything without first giving something in return.", author: "Edward Elric" },
  { quote: "Humankind cannot gain anything without first giving something in return.", author: "Fullmetal Alchemist" },
  { quote: "You should enjoy the little detours to the fullest, because that's where you'll find the things more important than what you want.", author: "Ling Yao" },
  { quote: "The only ones who should kill are those who are prepared to be killed.", author: "Fullmetal Alchemist" },
  { quote: "It's all right to cry. You're alive.", author: "Alphonse Elric" },
  { quote: "If you're gonna be a joke, be the funniest one there is.", author: "Roy Mustang" },
  { quote: "A hero would return the favor in kind, but a villain would use it as a chance to strike.", author: "Fullmetal Alchemist" },
  { quote: "You're only given a little spark of madness. You mustn't lose it.", author: "Robin Williams" },
  { quote: "Plus Ultra!", author: "All Might, My Hero Academia" },
  { quote: "It's fine to fumble around because we only live once. Nobody knows what comes next.", author: "Katsuki Bakugo" },
  { quote: "A hero is always ready to risk his life for someone else.", author: "All Might" },
  { quote: "Sometimes I do feel like I'm a failure. Like there's no hope for me.", author: "Izuku Midoriya" },
  { quote: "The moment you think of giving up, think of the reason why you held on so long.", author: "Natsu Dragneel" },
  { quote: "I don't want to conquer anyone. I just think the person with the most freedom in this whole sea... is the Pirate King!", author: "Monkey D. Luffy" },
  { quote: "Crying doesn't mean you're weak. It just means you've been strong for too long.", author: "Natsu Dragneel" },
  { quote: "If you die, I'll never forgive you.", author: "Erza Scarlet" },
  { quote: "A person grows up when he's able to overcome hardships.", author: "Makarov Dreyar" },
  { quote: "Human beings have the right to think they're invincible, even if it's a mistake, no matter what.", author: "Makarov Dreyar" },
  { quote: "You should enjoy the little detours. To the fullest. Because that's where you'll find the things more important than what you want.", author: "Fullmetal Alchemist" },
  { quote: "The world isn't perfect. But it's there for us, doing the best it can.", author: "Roy Mustang" },
  { quote: "A dropout will beat a genius through hard work.", author: "Rock Lee" },
  { quote: "I've decided. I'm gonna become a hero even if it kills me.", author: "Deku" },
  { quote: "Being weak is nothing to be ashamed of. Staying weak is.", author: "Fuegoleon Vermillion" },
  { quote: "No matter how hopeless a situation may seem, never give up.", author: "Asta" },
  { quote: "I'm not gonna run away, I never go back on my word! That's my nindo, my ninja way!", author: "Naruto Uzumaki" },
  { quote: "When people are protecting something truly special to them, they truly can become as strong as they can be.", author: "Naruto Uzumaki" },
  { quote: "The pain of being alone... I understand it more than any of you.", author: "Naruto Uzumaki" },
  { quote: "It's not the face that makes someone a monster; it's the choices they make with their life.", author: "Naruto Uzumaki" },
  { quote: "Talent is not what makes you different from someone else. It's your choices.", author: "Naruto Uzumaki" },
  { quote: "A ninja's greatest enemy isn't a shinobi from another village. It's their own hearts.", author: "Naruto Uzumaki" },
  { quote: "In order for people to understand one another, it's necessary to fight.", author: "Nagato, Naruto" },
  { quote: "There is a saying that goes 'When a man learns to love, he must bear the risk of hatred.'", author: "Jiraiya" },
  { quote: "The reason people can't forgive one another is because their hearts are weak.", author: "Sasuke Uchiha" },
  { quote: "People's lives don't end when they die. It ends when they lose faith.", author: "Itachi Uchiha" },
  { quote: "Sometimes the pain of loss can motivate us to grow.", author: "Itachi Uchiha" },
  { quote: "There's no need to rush things. Even a dream you chase after slowly won't run away from you.", author: "Konohamaru Sarutobi" },
  { quote: "The moment people come to know true despair, is when they know true peace.", author: "Uchiha Madara" },
  { quote: "Dreams don't come true just because you wish for them. It's your effort that makes them come true.", author: "Guy Sensei" },
  { quote: "I'll take a potato chip... and eat it!", author: "Light Yagami, Death Note" },
  { quote: "The world is rotten, and those who are making it rot deserve to die.", author: "Light Yagami" },
  { quote: "I am justice!", author: "Light Yagami" },
  { quote: "Whatever you do in life, it will not amount to much, but it is important that you did it.", author: "L, Death Note" },
  { quote: "There's no logic in giving up.", author: "L, Death Note" },
  { quote: "If you win, you live. If you lose, you die. If you don't fight, you can't win.", author: "Eren Yeager, Attack on Titan" },
  { quote: "The world is cruel, but it's also very beautiful.", author: "Mikasa Ackerman" },
  { quote: "If you don't fight, you can't win!", author: "Eren Yeager" },
  { quote: "This world is merciless, and it's also very beautiful.", author: "Mikasa Ackerman" },
  { quote: "Power is not an illusion, it's real, and reality is always cruel.", author: "Zeke Yeager" },
  { quote: "Keep moving forward, no matter how vast the fear, or how great the sadness.", author: "Attack on Titan" },
  { quote: "I want to see it, the outside world.", author: "Armin Arlert" },
  { quote: "I have to save this world, no matter what path I must take.", author: "Armin Arlert" },
  { quote: "Study your surroundings and use every piece of it to your advantage.", author: "Levi Ackerman" },
  { quote: "The only thing we're allowed to do is believe that we won't regret the choice we made.", author: "Levi Ackerman" },
  { quote: "Giving up? I still haven't even tried.", author: "Levi Ackerman" },
  { quote: "It's not about being invincible, it's about protecting what matters most.", author: "Levi Ackerman" },
  { quote: "A person who can't sacrifice anything can never change anything.", author: "Armin Arlert" },
  { quote: "Whether or not we regret our choices, we still have to choose something.", author: "Levi Ackerman" },
  { quote: "The world is merciless, but it's also beautiful.", author: "Attack on Titan" },
  { quote: "I'm going to become the King of the Pirates!", author: "Monkey D. Luffy" },
  { quote: "The only thing worse than being alone is wishing you were.", author: "Rin Okumura, Blue Exorcist" },
  { quote: "Even if you're a demon, you can still be good.", author: "Rin Okumura" },
  { quote: "A lesson learned the hard way is a lesson well learned.", author: "Blue Exorcist" },
  { quote: "Power is not determined by the size of your body but by the size of your heart and dreams.", author: "Monkey D. Luffy" },
  { quote: "Have you ever felt so much regret in your life that you thought your chest was gonna cave in?", author: "Levi Ackerman" },
  { quote: "I want to know what it means to be alive.", author: "Motoko Kusanagi, Ghost in the Shell" },
  { quote: "If we all reacted the same way, we'd be predictable, and there's always more than one way to view a situation.", author: "Motoko Kusanagi" },
  { quote: "What's important is whether you can act on your beliefs.", author: "Motoko Kusanagi" },
  { quote: "Overspecialize and you breed in weakness.", author: "Motoko Kusanagi" },
  { quote: "There are 8 million ways to be a good witch and only one way to be a bad one.", author: "Kiki's Delivery Service" },
  { quote: "Even a hint of hatred for someone can prevent all understanding.", author: "Nausicaa" },
  { quote: "The wind is a little cold, but it's blowing in a good direction.", author: "Nausicaa" },
  { quote: "I don't need luck. I need people who never give up.", author: "Studio Ghibli" },
  { quote: "Once you do something, you never forget. Even if you can't remember.", author: "Zeniba, Spirited Away" },
  { quote: "One who has known true bitterness will find great delight in the little joys of life.", author: "Spirited Away" },
  { quote: "There are things that even I don't want to see anymore.", author: "Haku, Spirited Away" },
  { quote: "You must fight. That is how you make your way in this world.", author: "Howl, Howl's Moving Castle" },
  { quote: "I finally have a reason to protect you.", author: "Howl's Moving Castle" },
  { quote: "A heart's weight in life is measured in memories.", author: "Studio Ghibli" },
  { quote: "It's never too late to start over.", author: "Studio Ghibli" },
  { quote: "The tiger and rabbit will be friends and love each other.", author: "Wolf's Rain" },
  { quote: "In this world, wherever there is light, there are also shadows.", author: "Kakashi Hatake, Naruto" },
  { quote: "Those who break the rules are trash, but those who abandon their friends are worse than trash.", author: "Kakashi Hatake" },
  { quote: "You're wrong. Not being able to protect your comrades doesn't make you trash.", author: "Obito Uchiha" },
  { quote: "As long as people continue to feel joy, sadness, and anger toward each other, hatred will never disappear.", author: "Nagato" },
  { quote: "You should be more afraid of not changing than of change itself.", author: "Naruto Shippuden" },
  { quote: "Life is not a game of luck. If you wanna win, work hard.", author: "Sora, No Game No Life" },
  { quote: "It's not the strength of the body that counts, but the strength of the spirit.", author: "J.R.R. Tolkien" },
  { quote: "Even the smallest person can change the course of the future.", author: "Galadriel, The Lord of the Rings" },
  { quote: "All we have to decide is what to do with the time that is given us.", author: "Gandalf" },
  { quote: "There is some good in this world, and it's worth fighting for.", author: "Samwise Gamgee" },
  { quote: "It's the job that's never started as takes longest to finish.", author: "Samwise Gamgee" },
  { quote: "A day may come when the courage of men fails.", author: "Aragorn, The Lord of the Rings" },
  { quote: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "Arwen" },
  { quote: "Even the smallest of people can change the course of the future.", author: "Galadriel" },
  { quote: "One does not simply walk into Mordor.", author: "Boromir" },
  { quote: "You shall not pass!", author: "Gandalf" },
  { quote: "My precious.", author: "Gollum" },
  { quote: "All that is gold does not glitter.", author: "J.R.R. Tolkien" },
  { quote: "It's the job that's never started as takes longest to finish.", author: "J.R.R. Tolkien" },
  { quote: "Even the wise cannot see all ends.", author: "Gandalf" },
  { quote: "The world is indeed full of peril, and in it there are many dark places.", author: "Gandalf" },
  { quote: "So do all who live to see such times, but that is not for them to decide.", author: "Gandalf" },
  { quote: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { quote: "There is nothing like looking, if you want to find something.", author: "J.R.R. Tolkien" },
  { quote: "Faithless is he that says farewell when the road darkens.", author: "J.R.R. Tolkien" },
  { quote: "I will not say do not weep, for not all tears are an evil.", author: "J.R.R. Tolkien" },
  { quote: "Deserves it! I daresay he does. Many that live deserve death.", author: "Gandalf" },
  { quote: "It's a dangerous business, going out your door.", author: "Bilbo Baggins" },
  { quote: "Home is behind, the world ahead.", author: "J.R.R. Tolkien" },
  { quote: "I wish it need not have happened in my time.", author: "Frodo Baggins" },
  { quote: "So do all who live to see such times.", author: "Gandalf" },
  { quote: "It is not despair, for despair is only for those who see the end beyond all doubt.", author: "Gandalf" },
  { quote: "Even the smallest act of kindness can change everything.", author: "Unknown" },
  { quote: "I am no man!", author: "Eowyn, The Lord of the Rings" },
  { quote: "There's some good in this world, Mr. Frodo, and it's worth fighting for.", author: "Samwise Gamgee" },
  { quote: "Fly, you fools!", author: "Gandalf" },
  { quote: "The board is set, the pieces are moving.", author: "Gandalf" },
  { quote: "Courage is found in unlikely places.", author: "J.R.R. Tolkien" },
  { quote: "All we have to decide is what to do with the time that is given to us.", author: "Gandalf" },
  { quote: "It is not the strength of the body, but the strength of the spirit that matters.", author: "J.R.R. Tolkien" }
];

export default function handler(req, res) {
  const random = quotes[Math.floor(Math.random() * quotes.length)];
  res.status(200).json(random);
}
